version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: springbootdemo-db
    environment:
      POSTGRES_DB: springbootdemo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hcadmin
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - abcd

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    networks:
      - abcd

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - abcd


  mongodb:
    image: mongo:latest
    container_name: springbootdemo-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: springbootdemo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - abcd


volumes:
  postgres_data:
  mongo_data:

networks:
  abcd:
    driver: bridge
