version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: springbootdemo-db
    environment:
      POSTGRES_DB: springbootdemo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hcadmin
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:latest
    container_name: springbootdemo-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: springbootdemo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db


volumes:
  postgres_data:
  mongo_data:
